### PR TITLE
Multiple version support for nodejs

### PR DESCRIPTION
**Pull request by rajesh-rajagopal**

### CODE REVIEW

**Comment by indykish** [comment]
@vijaykanthm28  Can you review this pull request ?

**Comment by indykish** [comment]
@rajesh-rajagopal  Nice job.  Learn other tools as well.

**Comment by rajesh-rajagopal** [comment]
Thank You sir. i will learn quickly..

**Comment by indykish** [comment]
@rajesh-rajagopal  Is this getting tested in the current builds ?

**Pull request merged**
